import type { Doctor } from "@/types/doctor";

export const doctors: Doctor[] = [
  {
    id: "doc-101",
    name: "Dr. Kumar Das",
    specialty: "Cardiologist",
    qualification: "MBBS, MD (Internal Medicine)",
    experienceYears: 15,
    clinic: "Sanskara Heart Clinic",
    location: "Dombivali, Mumbai",
    rating: 4.8,
    reviewsCount: 4942,
    patientsCount: 5000,
    consultationFee: 600,
    availableToday: true,
    timing: "10:00 AM - 5:00 PM",
    bio: "15+ years of experience in all aspects of cardiology, including non-invasive and interventional procedures.",
    avatarInitials: "KD",
  },
  {
    id: "doc-102",
    name: "Dr. Prakash Das",
    specialty: "Psychologist",
    qualification: "MBBS, MD (Psychiatry)",
    experienceYears: 7,
    clinic: "Mindwell Counselling Center",
    location: "Kolkata",
    rating: 4.7,
    reviewsCount: 1820,
    patientsCount: 3200,
    consultationFee: 500,
    availableToday: true,
    timing: "09:30 AM - 7:00 PM",
    bio: "Senior psychologist practicing for 7+ years, focused on anxiety, stress management, and family counselling.",
    avatarInitials: "PD",
  },
  {
    id: "doc-103",
    name: "Dr. Anika Rao",
    specialty: "General Physician",
    qualification: "MBBS, DNB (General Medicine)",
    experienceYears: 10,
    clinic: "City Wellness Clinic",
    location: "Baharampur, West Bengal",
    rating: 4.6,
    reviewsCount: 2210,
    patientsCount: 4100,
    consultationFee: 400,
    availableToday: true,
    timing: "09:00 AM - 2:00 PM",
    bio: "General physician handling everyday illness, chronic condition follow-ups, and preventive health checks.",
    avatarInitials: "AR",
  },
  {
    id: "doc-104",
    name: "Dr. Martin Cole",
    specialty: "Dermatologist",
    qualification: "MBBS, MD (Dermatology)",
    experienceYears: 9,
    clinic: "Skin & Glow Clinic",
    location: "Kolkata",
    rating: 4.5,
    reviewsCount: 1390,
    patientsCount: 2600,
    consultationFee: 550,
    availableToday: false,
    timing: "11:00 AM - 6:00 PM",
    bio: "Dermatologist specialising in acne, skin allergies, and cosmetic dermatology consultations.",
    avatarInitials: "MC",
  },
  {
    id: "doc-105",
    name: "Dr. Sunita Verma",
    specialty: "Pediatrician",
    qualification: "MBBS, MD (Pediatrics)",
    experienceYears: 12,
    clinic: "Little Steps Children's Clinic",
    location: "Kolkata",
    rating: 4.9,
    reviewsCount: 3105,
    patientsCount: 6000,
    consultationFee: 450,
    availableToday: true,
    timing: "10:00 AM - 4:00 PM",
    bio: "Pediatrician with 12 years of experience in child growth, vaccination, and newborn care.",
    avatarInitials: "SV",
  },
  {
    id: "doc-106",
    name: "Dr. Rohit Sen",
    specialty: "Orthopedic",
    qualification: "MBBS, MS (Orthopedics)",
    experienceYears: 11,
    clinic: "Bone & Joint Care Centre",
    location: "Baharampur, West Bengal",
    rating: 4.4,
    reviewsCount: 980,
    patientsCount: 2100,
    consultationFee: 500,
    availableToday: false,
    timing: "12:00 PM - 6:00 PM",
    bio: "Orthopedic surgeon treating joint pain, fractures, and sports injuries with modern rehab-focused care.",
    avatarInitials: "RS",
  },
];

